title: Michelle Sy  
author: Michelle Sy 
email: msy@ebnet.org
description: > # this means to ignore newlines until "baseurl:"
  This is my final project for AP CS. 
theme: minima
# social links
twitter_username: immichellesy # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
