title: All About Michelle Sy 
author: Michelle Sy 
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Hi, I'm Michelle and welcome to my website. 
  Brag sheet for high-school: 
  1. I won Most Valuable Offensive Player Award for field hockey
  2. I learned photography 
  3. I received the President's Volunteer Service Award
theme: minima
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
